name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.81.0
          HUGO_EXTENDED: true
          TARGET_REPO: asrafulashiq/asrafulashiq.github.io
          TARGET_BRANCH: master
          TOKEN: ${{ secrets.MY_TOKEN }}
          HUGO_ARGS: '-t academic'
          CNAME: asrafulashiq.github.io